modLoader="javafml"
loaderVersion="[47,)"
license="${license}"
issueTrackerURL="${issues_url}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
logo="packmode/logo.png"
description='''${description}
'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"